library(shiny)
library(ggplot2)
library(plotly)
library(rbokeh)
library(highcharter)
library(descriptr)
library(olsrr)
library(inferr)
library(dplyr)
library(grid)
library(gridExtra)
library(purrr)
library(tidyr)
library(tibble)
library(readxl)
library(readr)
library(jsonlite)
library(magrittr)
library(tools)
library(caret)
library(lubridate)
library(scales)
library(stringr)

shinyServer(function(input, output, session) {

	source('logic/logic_dataoptions.R', local = T)
    source('logic/logic_upload.R', local = T)
    source('logic/logic_transform2.R', local = T)
    source('logic/logic_select.R', local = T)
    source('logic/logic_filter.R', local = T)
    source('logic/logic_screen.R', local = T)
    source('logic/logic_sample.R', local = T)
    source('logic/logic_partition.R', local = T)
    source('logic/logic_view.R', local = T)
    source('logic/logic_summary.R', local = T)
    source('logic/logic_freq_qual.R', local = T)
    source('logic/logic_freq_quant.R', local = T)
    source('logic/logic_cross.R', local = T)
    source('logic/logic_mult1.R', local = T)
    source('logic/logic_mult2.R', local = T)
    source('logic/logic_group_summary.R', local = T)
    source('logic/logic_ttest.R', local = T)
    source('logic/logic_itest.R', local = T)
    source('logic/logic_ptest.R', local = T)
    source('logic/logic_binomtest.R', local = T)
    source('logic/logic_osvar.R', local = T)
    source('logic/logic_tsvar.R', local = T)
    source('logic/logic_osprop.R', local = T)
    source('logic/logic_tsprop.R', local = T)
    source('logic/logic_anova.R', local = T)
    source('logic/logic_levene.R', local = T)
    source('logic/logic_chigof.R', local = T)
    source('logic/logic_chict.R', local = T)
    source('logic/logic_cochran.R', local = T)
    source('logic/logic_runs.R', local = T)
    source('logic/logic_mcnemar.R', local = T)
    source('logic/logic_binom.R', local = T)
    source('logic/logic_f.R', local = T)
    source('logic/logic_t.R', local = T)
    source('logic/logic_norm.R', local = T)
    source('logic/logic_chisq.R', local = T)
    source('logic/logic_bar.R', local = T)
    source('logic/logic_bar2.R', local = T)
    source('logic/logic_box.R', local = T)
    source('logic/logic_box2.R', local = T)
    source('logic/logic_hist.R', local = T)
    source('logic/logic_line.R', local = T)
    source('logic/logic_pie.R', local = T)
    source('logic/logic_pie3d.R', local = T)
    source('logic/logic_scatter.R', local = T)
    source('logic/logic_regress.R', local = T)
    source('logic/logic_mselection2.R', local = T)
    source('logic/logic_resdiagtrial.R', local = T)
    source('logic/logic_hetero.R', local = T)
    source('logic/logic_collin.R', local = T)
    source('logic/logic_inflobs2.R', local = T)
    source('logic/logic_mfit2.R', local = T)
    source('logic/logic_regdiag.R', local = T)
    source('logic/logic_gscatter.R', local = T)
    source('logic/logic_home.R', local = T)
    source('logic/logic_vizlib.R', local = T)
    source('logic/logic_gbar.R', local = T)
    source('logic/logic_gbar2.R', local = T)
    source('logic/logic_gbox.R', local = T)
    source('logic/logic_gbox2.R', local = T)
    source('logic/logic_ghist.R', local = T)
    source('logic/logic_gpie.R', local = T)
    source('logic/logic_gline.R', local = T)
    source('logic/logic_gline2.R', local = T)
    source('logic/logic_bar_plot_1.R', local = T)
    source('logic/logic_bar_plot_2.R', local = T)
    source('logic/logic_box_plot_1.R', local = T)
    source('logic/logic_box_plot_2.R', local = T)
    source('logic/logic_scatter_prh.R', local = T)
    source('logic/logic_line_prh.R', local = T)
    source('logic/logic_hist_prh.R', local = T)
    source('logic/logic_pie_prh.R', local = T)
})


